# Generated by Django 4.2.16 on 2026-06-24 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WatchItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("movie", "Movie"),
                            ("series", "TV Series"),
                            ("anime", "Anime"),
                            ("documentary", "Documentary"),
                        ],
                        default="series",
                        max_length=20,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("netflix", "Netflix"),
                            ("prime", "Amazon Prime"),
                            ("hotstar", "Disney+ Hotstar"),
                            ("jiocinema", "JioCinema"),
                            ("youtube", "YouTube"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("watching", "Watching"),
                            ("completed", "Completed"),
                            ("dropped", "Dropped"),
                            ("plan_to_watch", "Plan to Watch"),
                            ("on_hold", "On Hold"),
                        ],
                        default="plan_to_watch",
                        max_length=20,
                    ),
                ),
                ("total_seasons", models.IntegerField(blank=True, null=True)),
                ("watched_seasons", models.IntegerField(default=0)),
                ("total_episodes", models.IntegerField(blank=True, null=True)),
                ("watched_episodes", models.IntegerField(default=0)),
                (
                    "personal_rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Personal rating out of 10",
                        max_digits=3,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "genres",
                    models.JSONField(default=list, help_text="List of genre strings"),
                ),
                ("tags", models.JSONField(default=list, help_text="Custom tags")),
                ("started_watching", models.DateField(blank=True, null=True)),
                ("finished_watching", models.DateField(blank=True, null=True)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tmdb_id",
                    models.IntegerField(
                        blank=True, help_text="TMDB ID for metadata fetch", null=True
                    ),
                ),
                ("poster_url", models.URLField(blank=True, max_length=500)),
                ("release_year", models.IntegerField(blank=True, null=True)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("language", models.CharField(blank=True, max_length=100)),
                (
                    "notify_new_season",
                    models.BooleanField(
                        default=True,
                        help_text="Get notified when a new season releases",
                    ),
                ),
                ("last_notified_season", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="WatchNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season", models.IntegerField(blank=True, null=True)),
                ("episode", models.IntegerField(blank=True, null=True)),
                ("content", models.TextField()),
                (
                    "rating",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watch_notes",
                        to="watchlist.watchitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
