# Generated by Django 4.2.16 on 2026-05-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="backend_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="ci_cd_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="deployment_type",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="project",
            name="docker_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="frontend_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="health_endpoint",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="hosting_provider",
            field=models.CharField(
                blank=True,
                choices=[
                    ("vercel", "Vercel"),
                    ("render", "Render"),
                    ("railway", "Railway"),
                    ("aws", "AWS"),
                    ("digitalocean", "DigitalOcean"),
                    ("vps", "VPS"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
