# Generated by Django 4.2.16 on 2026-07-04 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_project_backend_url_project_ci_cd_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="alias",
            field=models.SlugField(
                blank=True,
                help_text="Subdomain alias e.g. 'agripool' → agripool.bhaumikjangid.me",
                max_length=100,
            ),
        ),
    ]
