# Generated by Django 4.2.16 on 2026-05-19 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0002_project_backend_url_project_ci_cd_enabled_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_resolved", models.BooleanField(default=False)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incidents",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="HealthCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("checked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("healthy", "Healthy"),
                            ("unhealthy", "Unhealthy"),
                            ("timeout", "Timeout"),
                            ("error", "Error"),
                        ],
                        max_length=20,
                    ),
                ),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("latency_ms", models.IntegerField(blank=True, null=True)),
                ("is_healthy", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_checks",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-checked_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "-checked_at"],
                        name="monitoring__project_758801_idx",
                    )
                ],
            },
        ),
    ]
