# Generated by Django 4.2.16 on 2026-06-24 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enabled_services",
                    models.JSONField(
                        default=list, help_text="List of enabled microservice slugs"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site Configuration",
            },
        ),
        migrations.AlterModelOptions(
            name="pageview",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.RemoveIndex(
            model_name="pageview",
            name="core_pagevi_path_c9985e_idx",
        ),
        migrations.RenameField(
            model_name="dailystat",
            old_name="total_views",
            new_name="page_views",
        ),
        migrations.RenameField(
            model_name="dailystat",
            old_name="unique_paths",
            new_name="unique_visitors",
        ),
        migrations.RenameField(
            model_name="pageview",
            old_name="viewed_at",
            new_name="timestamp",
        ),
        migrations.RemoveField(
            model_name="pageview",
            name="country",
        ),
        migrations.AddField(
            model_name="pageview",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pageview",
            name="path",
            field=models.CharField(max_length=500),
        ),
    ]
