# Generated by Django 4.2.16 on 2026-05-20 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Academic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("10th", "10th Standard"),
                            ("12th", "12th Standard"),
                            ("diploma", "Diploma"),
                            ("btech", "B.Tech"),
                            ("mtech", "M.Tech"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("institution", models.CharField(max_length=200)),
                ("board_or_university", models.CharField(blank=True, max_length=200)),
                ("field_of_study", models.CharField(blank=True, max_length=100)),
                ("percentage_or_cgpa", models.CharField(max_length=20)),
                (
                    "scale",
                    models.CharField(
                        default="percentage",
                        help_text="e.g. percentage, 10-point CGPA, 4-point CGPA",
                        max_length=20,
                    ),
                ),
                ("start_year", models.IntegerField()),
                ("end_year", models.IntegerField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "start_year"],
            },
        ),
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("date", models.DateField(blank=True, null=True)),
                ("url", models.URLField(blank=True)),
                ("icon_name", models.CharField(blank=True, max_length=50)),
                ("order", models.IntegerField(default=0)),
                ("is_visible", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order", "-date"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("tagline", models.CharField(max_length=200)),
                ("bio", models.TextField()),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("location", models.CharField(blank=True, max_length=100)),
                ("github_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                (
                    "resume",
                    models.FileField(blank=True, null=True, upload_to="resume/"),
                ),
                (
                    "photo_primary",
                    models.ImageField(blank=True, null=True, upload_to="photos/"),
                ),
                (
                    "photo_secondary",
                    models.ImageField(blank=True, null=True, upload_to="photos/"),
                ),
                ("available_for_work", models.BooleanField(default=True)),
                ("years_of_experience", models.IntegerField(default=0)),
                ("leetcode_username", models.CharField(blank=True, max_length=100)),
                ("leetcode_solved", models.IntegerField(default=0)),
                ("leetcode_easy", models.IntegerField(default=0)),
                ("leetcode_medium", models.IntegerField(default=0)),
                ("leetcode_hard", models.IntegerField(default=0)),
                ("codeforces_username", models.CharField(blank=True, max_length=100)),
                ("codeforces_rating", models.IntegerField(default=0)),
                ("codechef_username", models.CharField(blank=True, max_length=100)),
                ("total_dsa_solved", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Profile",
            },
        ),
        migrations.AlterField(
            model_name="skill",
            name="icon_name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="skill",
            name="proficiency",
            field=models.IntegerField(default=80),
        ),
    ]
