# Generated by Django 4.2.16 on 2026-06-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_blogpost_category_blogpost_featured_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactsubmission",
            name="page",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
