# Generated by Django 4.2.16 on 2026-06-25 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_contactsubmission_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="hero_video",
            field=models.FileField(blank=True, null=True, upload_to="videos/"),
        ),
        migrations.AddField(
            model_name="profile",
            name="video_tooltips",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
