# Generated by Django 4.2.16 on 2026-06-25 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_profile_hero_video_profile_video_tooltips"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="hero_video",
            field=models.URLField(blank=True, null=True),
        ),
    ]
