# Generated by Django 4.2.16 on 2026-07-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0007_alter_profile_hero_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="hidden_github_repos",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of GitHub repo names to hide from portfolio",
            ),
        ),
    ]
