# Generated by Django 4.2.16 on 2026-05-19 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0002_project_backend_url_project_ci_cd_enabled_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Deployment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("in_progress", "In Progress"),
                            ("cancelled", "Cancelled"),
                            ("rolled_back", "Rolled Back"),
                        ],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("github_actions", "GitHub Actions"),
                            ("render", "Render"),
                            ("vercel", "Vercel"),
                            ("manual", "Manual"),
                            ("webhook", "Webhook"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("environment", models.CharField(default="production", max_length=20)),
                ("commit_hash", models.CharField(blank=True, max_length=40)),
                ("commit_message", models.TextField(blank=True)),
                ("branch", models.CharField(default="main", max_length=100)),
                ("triggered_by", models.CharField(blank=True, max_length=100)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.IntegerField(blank=True, null=True)),
                ("logs", models.TextField(blank=True)),
                ("error_message", models.TextField(blank=True)),
                ("deployment_url", models.URLField(blank=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deployments",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "-started_at"],
                        name="deployments_project_ee5a99_idx",
                    )
                ],
            },
        ),
    ]
